github_branch: main
github_project_repo: https://github.com/keptn/lifecycle-toolkit
github_repo: https://github.com/keptn/lifecycle-toolkit
github_subdir: docs

versions:
  - url: /docs/
    version: development
  - url: https://lifecycle-test.keptn.sh/docs
    version: latest
